# Skapa en modell 
som ger underlag för att köpa eller sälja kryptovaluta

In [5]:
import pandas as pd
import numpy as np
import binance
import momentum as mom

## Skapa train/test data

In [6]:
### Kör denna kod för att skapa en dataframe med train/test data ###
###               Gör interupt när tillräckligt finns            ###
# set timer
import time
start_time = time.time()
mom.start()
duration = time.time() - start_time

(1, 12)
[1626.82     nan     nan     nan]
(2, 13)
[1627.   nan   nan   nan]
(3, 13)
[1626.97     nan     nan     nan]
(4, 13)
[1626.48     nan     nan     nan]
(5, 13)
[1626.35  1626.724      nan      nan]
(6, 13)
[1626.68  1626.696      nan      nan]
(7, 13)
[1626.56  1626.608      nan      nan]
(8, 13)
[1626.1   1626.434      nan      nan]
(9, 13)
[1625.88  1626.314      nan      nan]
(10, 13)
[1625.99  1626.242      nan      nan]
(11, 13)
[1625.83  1626.072      nan      nan]


In [ ]:
duration = time.time() - start_time
# format duration to minutes and seconds
duration = divmod(duration, 60)
str_duration = str(duration[0]) + ' minutes and ' + str(int(duration[1])) + ' seconds'
print(str_duration )
print(mom.df.tail(10))
mom.df.to_csv('data.csv')
print(mom.df.shape)

In [8]:
use_features = mom.df.columns.tolist()

# write to file
with open('use_features.txt', 'w') as f:
    for item in use_features:
        f.write("%s " % item)
use_features

['pris',
 'sma_5',
 'sma_20',
 'm_strategy',
 'fib38',
 'fib50',
 'fib62',
 'f_strategy',
 'boll_sma',
 'boll_std',
 'upper_band',
 'lower_band',
 'b_strategy']

### y-värdena: en plus två tidseneheter framåt i df

In [1]:
import pandas as pd
import numpy as np
import binance


In [14]:
client = binance.Client()
r = client.get_historical_klines('ETHBTC', client.KLINE_INTERVAL_1MINUTE, '1-Jan-2023', '20-Jan-2023')
df = pd.DataFrame(r,columns=['datum', 'open','low','high','close','volume','close_time','quote_asset_volume','number_of_trades','taker_buy_base_asset_volume','taker_buy_quote_asset_volume','ignore'])
df = df[['datum','open','high','low','close','volume']]
# OHLCV values (Open time, Open, High, Low, Close, Volume, Close time, Quote asset volume, 
# Number of trades, Taker buy base asset volume, Taker buy quote asset volume, Ignore)
df.datum = pd.to_datetime(df.datum, unit='ms')
df.set_index('datum', inplace=True)

# set all columns numeric
df = df.apply(pd.to_numeric, errors='coerce')

In [ ]:
print(df.info())
print(df.shape)
print(df.columns)

Prepare data for training and testing

In [51]:
# read use_features.txt file
with open('use_features.txt', 'r') as f:
    use_features = f.read().split() 
    
# set all use_features to np.nan
for feature in use_features:
    df[feature] = np.nan

df.pris = df.close

df['y_1'] = df.pris.shift(-1)  # y_1 = pris(t+1)
df['y_2'] = df.pris.shift(-2)  # y_2 = pris(t+2)

# df['sma_5'] = df.pris.rolling(5).mean()
# df['sma_20'] = df.pris.rolling(20).mean()
df[use_features]



pris  sma_5  sma_20  m_strategy  fib38  fib50  fib62  \
datum                                                                           
2023-01-01 00:00:00  0.072303    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-01 00:01:00  0.072316    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-01 00:02:00  0.072321    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-01 00:03:00  0.072329    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-01 00:04:00  0.072329    NaN     NaN         NaN    NaN    NaN    NaN   
...                       ...    ...     ...         ...    ...    ...    ...   
2023-01-19 23:56:00  0.073637    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-19 23:57:00  0.073619    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-19 23:58:00  0.073616    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-19 23:59:00  0.073615    NaN     NaN         NaN    NaN    NaN    NaN   
2023-01-20 00:00:00  0.073591    NaN     NaN         NaN    NaN    NaN    NaN   

                     f_strategy  boll_sma  boll_std  upper_band  lower_band  \
datum                                                                         
2023-01-01 00:00:00         NaN       NaN       NaN         NaN         NaN   
2023-01-01 00:01:00         NaN       NaN       NaN         NaN         NaN   
2023-01-01 00:02:00         NaN       NaN       NaN         NaN         NaN   
2023-01-01 00:03:00         NaN       NaN       NaN         NaN         NaN   
2023-01-01 00:04:00         NaN       NaN       NaN         NaN         NaN   
...                         ...       ...       ...         ...         ...   
2023-01-19 23:56:00         NaN       NaN       NaN         NaN         NaN   
2023-01-19 23:57:00         NaN       NaN       NaN         NaN         NaN   
2023-01-19 23:58:00         NaN       NaN       NaN         NaN         NaN   
2023-01-19 23:59:00         NaN       NaN       NaN         NaN         NaN   
2023-01-20 00:00:00         NaN       NaN       NaN         NaN         NaN   

                     b_strategy  
datum                            
2023-01-01 00:00:00         NaN  
2023-01-01 00:01:00         NaN  
2023-01-01 00:02:00         NaN  
2023-01-01 00:03:00         NaN  
2023-01-01 00:04:00         NaN  
...                         ...  
2023-01-19 23:56:00         NaN  
2023-01-19 23:57:00         NaN  
2023-01-19 23:58:00         NaN  
2023-01-19 23:59:00         NaN  
2023-01-20 00:00:00         NaN  

[27361 rows x 13 columns]

In [54]:
mom.df = df[use_features+['y_1','y_2']].copy()
mom.df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 27361 entries, 2023-01-01 00:00:00 to 2023-01-20 00:00:00
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pris        27361 non-null  float64
 1   sma_5       0 non-null      float64
 2   sma_20      0 non-null      float64
 3   m_strategy  0 non-null      float64
 4   fib38       0 non-null      float64
 5   fib50       0 non-null      float64
 6   fib62       0 non-null      float64
 7   f_strategy  0 non-null      float64
 8   boll_sma    0 non-null      float64
 9   boll_std    0 non-null      float64
 10  upper_band  0 non-null      float64
 11  lower_band  0 non-null      float64
 12  b_strategy  0 non-null      float64
 13  y_1         27360 non-null  float64
 14  y_2         27359 non-null  float64
dtypes: float64(15)
memory usage: 4.3 MB


In [55]:
mom.trading_logic()

print(mom.df.info())
mom.df.tail(10)

(27361, 15)
[0.073591   0.0736156  0.07360453 0.07354782]
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 27361 entries, 2023-01-01 00:00:00 to 2023-01-20 00:00:00
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pris        27361 non-null  float64
 1   sma_5       27357 non-null  float64
 2   sma_20      27342 non-null  float64
 3   m_strategy  27361 non-null  object 
 4   fib38       27341 non-null  float64
 5   fib50       27341 non-null  float64
 6   fib62       27341 non-null  float64
 7   f_strategy  27361 non-null  object 
 8   boll_sma    27342 non-null  float64
 9   boll_std    27342 non-null  float64
 10  upper_band  27342 non-null  float64
 11  lower_band  27342 non-null  float64
 12  b_strategy  27361 non-null  object 
 13  y_1         27360 non-null  float64
 14  y_2         27359 non-null  float64
dtypes: float64(12), object(3)
memory usage: 4.3+ MB
None


pris     sma_5    sma_20 m_strategy     fib38  \
datum                                                                    
2023-01-19 23:51:00  0.073552  0.073571  0.073585       sell  0.073587   
2023-01-19 23:52:00  0.073573  0.073568  0.073583       hold  0.073587   
2023-01-19 23:53:00  0.073573  0.073566  0.073582       hold  0.073587   
2023-01-19 23:54:00  0.073573  0.073566  0.073582       hold  0.073587   
2023-01-19 23:55:00  0.073588  0.073572  0.073583        buy  0.073587   
2023-01-19 23:56:00  0.073637  0.073589  0.073586        buy  0.073605   
2023-01-19 23:57:00  0.073619  0.073598  0.073588        buy  0.073605   
2023-01-19 23:58:00  0.073616  0.073607  0.073589        buy  0.073605   
2023-01-19 23:59:00  0.073615  0.073615  0.073591       hold  0.073605   
2023-01-20 00:00:00  0.073591  0.073616  0.073591       hold  0.073605   

                        fib50     fib62 f_strategy  boll_sma  boll_std  \
datum                                                                    
2023-01-19 23:51:00  0.073580  0.073573       hold  0.073585  0.000014   
2023-01-19 23:52:00  0.073580  0.073573       hold  0.073583  0.000014   
2023-01-19 23:53:00  0.073580  0.073573       hold  0.073582  0.000014   
2023-01-19 23:54:00  0.073580  0.073573       hold  0.073582  0.000014   
2023-01-19 23:55:00  0.073580  0.073573        buy  0.073583  0.000014   
2023-01-19 23:56:00  0.073595  0.073584       hold  0.073586  0.000018   
2023-01-19 23:57:00  0.073595  0.073584       hold  0.073588  0.000020   
2023-01-19 23:58:00  0.073595  0.073584       hold  0.073589  0.000021   
2023-01-19 23:59:00  0.073595  0.073584       hold  0.073591  0.000021   
2023-01-20 00:00:00  0.073595  0.073584       hold  0.073591  0.000021   

                     upper_band  lower_band b_strategy       y_1       y_2  
datum                                                                       
2023-01-19 23:51:00    0.073613    0.073556       hold  0.073573  0.073573  
2023-01-19 23:52:00    0.073610    0.073556       hold  0.073573  0.073573  
2023-01-19 23:53:00    0.073610    0.073555       hold  0.073573  0.073588  
2023-01-19 23:54:00    0.073610    0.073554       hold  0.073588  0.073637  
2023-01-19 23:55:00    0.073611    0.073555       hold  0.073637  0.073619  
2023-01-19 23:56:00    0.073622    0.073550       sell  0.073619  0.073616  
2023-01-19 23:57:00    0.073627    0.073548       hold  0.073616  0.073615  
2023-01-19 23:58:00    0.073630    0.073548       hold  0.073615  0.073591  
2023-01-19 23:59:00    0.073633    0.073548       hold  0.073591       NaN  
2023-01-20 00:00:00    0.073633    0.073548       hold       NaN       NaN

In [56]:
print(mom.df.m_strategy.value_counts())
print(mom.df.b_strategy.value_counts())
print(mom.df.f_strategy.value_counts())


sell    9844
buy     9598
hold    7919
Name: m_strategy, dtype: int64
hold    25892
buy       740
sell      729
Name: b_strategy, dtype: int64
hold    24738
sell     1318
buy      1305
Name: f_strategy, dtype: int64


RandomForrestClassifier

In [57]:
from sklearn.ensemble import RandomForestClassifier


In [108]:
# select the 20% last rows for test
test = mom.df.iloc[-int(mom.df.shape[0]*0.2):].copy()
train = mom.df[~mom.df.index.isin(test.index)].copy()
test = test.dropna().copy()
train= train.dropna().copy()

# set y_test to 1 if y_1 > pris else 0
y_test = pd.Series(np.where(test['y_1'] > test['pris'], 1, 0))
y_train = pd.Series(np.where(train['y_1'] > train['pris'], 1, 0))
X_test = test[use_features].copy()
X_train= train[use_features].copy()

# replace 'hold' with 0, 'buy' with 1 and 'sell' with -1
X_train.replace({'hold':0.0, 'buy':1.0, 'sell':-1.0}, inplace=True)
X_test.replace({'hold':0.0, 'buy':1.0, 'sell':-1.0}, inplace=True)

In [94]:
print(X_test.shape, y_test.shape)
print(X_train.shape, y_train.shape)

(5470, 13) (5470,)
(21869, 13) (21869,)


In [124]:
print(np.array(X_test.pris))
print(np.array(y_test))

[0.074339 0.074357 0.074377 ... 0.073637 0.073619 0.073616]
[1 1 0 ... 0 0 0]


In [127]:
# create model
rfc = RandomForestClassifier(n_estimators=1000, max_depth=12, random_state=0, n_jobs=-1)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)
y_train_pred = rfc.predict(X_train)

from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(roc_auc_score(y_test, y_pred))


[[2506  453]
 [2147  364]]
0.5246800731261426
0.4959349527842952
[[12801    72]
 [ 6431  2565]]


In [128]:

print(confusion_matrix(y_train, y_train_pred))
print(accuracy_score(y_train, y_train_pred))
print(roc_auc_score(y_train, y_train_pred))

[[12801    72]
 [ 6431  2565]]
0.7026384379715579
0.6397668105734661


In [105]:
y_train.value_counts()

0    12873
1     8996
dtype: int64